version: "3.9"

services:
  db:
    image: postgres:16
    container_name: vodnet_db
    environment:
      POSTGRES_USER: vodnet
      POSTGRES_PASSWORD: vodnet
      POSTGRES_DB: vodnet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vodnet"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: vodnet_backend
    environment:
      DB_URL: postgresql+psycopg2://vodnet:vodnet@db:5432/vodnet
      CORS_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

volumes:
  pgdata:

